### ISSUE TITLE
crash after upgrading from 2.8.0 to 2.9.0

### ISSUE THREAD

**Issue by hellodword** [Rongronggg9/RSS-to-Telegram-Bot#528]
## Describe the bug

I'm using Docker Compose, and it keeps crashing after upgrading. It works again if I downgrade to 2.8.0.

## To Reproduce

1. the id
```
$ id
uid=1001(ubuntu) gid=1001(ubuntu) groups=1001(ubuntu)
```
2. the docker-compose.yml

```yaml
# Please read https://github.com/Rongronggg9/RSS-to-Telegram-Bot/blob/master/docs/deployment-guide.md for more details.
version: '3.6'

# docker compose up --pull always --build -d

services:

  main:
    user: '1001:1001'
    image: rongronggg9/rss-to-telegram
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    env_file:
      - .env
    environment:
      - MULTIUSER=0  # default: 1
      - CRON_SECOND=59  # 0-59, default: 0
      - DATABASE_URL=sqlite:///app/config/db.sqlite3
      - USER_AGENT='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36'
      - HTTP_TIMEOUT=120  # default: 12
      - HTTP_CONCURRENCY=64  # default: 1024
      - HTTP_CONCURRENCY_PER_HOST=8  # default: 16
      - DEBUG=1  # debug logging, default: 0
```

Sorry, these are not exact reproduction steps since I'm using a mobile device, and it's difficult to deploy a new instance.

However, I believe I started with the docker-compose.yml at 2.7.0, then upgraded to 2.8.0, and finally 2.9.0.

## Screenshots

-

## Feed URL

-

## Expected behavior

It works.

## Important log

```
main-1  | Traceback (most recent call last):
main-1  |   File "/app/src/db/__init__.py", line 119, in close
main-1  |     await Tortoise.close_connections()
main-1  |   File "/opt/venv/lib/python3.12/site-packages/tortoise/__init__.py", line 551, in close_connections
main-1  |     await connections.close_all()
main-1  |   File "/opt/venv/lib/python3.12/site-packages/tortoise/connection.py", line 188, in close_all
main-1  |     tasks = [conn.close() for conn in self.all()]
main-1  |                                       ^^^^^^^^^^
main-1  |   File "/opt/venv/lib/python3.12/site-packages/tortoise/connection.py", line 177, in all
main-1  |     return [self.get(alias) for alias in self.db_config]
main-1  |                                          ^^^^^^^^^^^^^^
main-1  |   File "/opt/venv/lib/python3.12/site-packages/tortoise/connection.py", line 48, in db_config
main-1  |     raise ConfigurationError(
main-1  | tortoise.exceptions.ConfigurationError: DB configuration not initialised. Make sure to call Tortoise.init with a valid configuration before attempting to create connections.
main-1  | 2024-09-12-01:40:32:ERROR:RSStT - Exited with code 1
```
